services:
  server:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      MEMORY: "16384M"
      MAX_PLAYERS: "1000"
      ONLINE_MODE: "false"
      USE_AIKAR_FLAGS: "true"
      TZ: "America/Sao_Paulo"
      ENABLE_COMMAND_BLOCK: "true"
      SEED: "15051991"
      LEVEL: "Moria"
      # LEVEL_TYPE: "large_biomes"
      LEVEL_TYPE: "flat"
      DIFFICULTY: "peaceful"
      INIT_COMMAND: "gamerule doDaylightCycle false; time set day"
      ENFORCE_SECURE_PROFILE: "false"
    volumes:
      - "./server-data:/data"

  agents:
    tty: true
    stdin_open: true
    image: "mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm"
    user: "${UID}:${GID}"
    volumes:
      - "../ts-agents:/workspace"
